using System.Reflection;
using System.Text;
using ClosedXML.Excel;

namespace ExcelGenerator;

public static class EnumGenerator
{
    private static          Assembly?       _enumAssembly;
    private static          string?         _enumSource;
    private static readonly EnumCompiler    _enumCompiler       = new();
    private static readonly string          _enumAssemblyName   = "GeneratedEnums";
    
    
    // 시트 구조: 1행=필드 역할(EID/Name/Desc), 2행=설명, 3행=타입, 4행부터 데이터
    private const int HeaderRow = 1;
    private const int DataStartRow = 4;

    public static void GenerateEnumSource(string enumFilePath)
    {
        StringBuilder sb = new();

        // 예외를 삼키지 않는다. 파일 잠금 등 실패는 OpenWorkbook이 명확한 메시지로 던지고,
        // 그대로 위로 전파돼 파이프라인이 즉시 중단된다(뒤에서 "소스가 null"로 번지지 않도록).
        using var workbook = ExcelGenerator.OpenWorkbook(enumFilePath);

        var first = true;
        foreach (var worksheet in workbook.Worksheets)
        {
            if (!first)
                sb.AppendLine();
            first = false;

            AppendEnum(sb, worksheet);
        }

        // 생성 코드는 GameData 네임스페이스로 통일한다(서버/Unity에서 전역 오염 없이 참조).
        // 블록 네임스페이스로 감싸는 이유는 CodeGenUtil 주석 참조(Unity = C# 9).
        _enumSource = CodeGenUtil.BuildFile("GameData", Array.Empty<string>(), sb.ToString());
        _enumAssembly = _enumCompiler.Compile(_enumSource, _enumAssemblyName);
    }

    public static bool HasMember(string enumName, string memberName)
    {
        if (null == _enumAssembly)
        {
            throw new Exception("Enum이 Compile되지 않아서 null 입니다. 종료합니다.");
        }
            
        return _enumCompiler.HasMember(_enumAssembly, enumName, memberName);
    }

    private static void AppendEnum(StringBuilder sb, IXLWorksheet worksheet)
    {
        // 1행에서 EID/Name/Desc 컬럼 위치를 찾는다.
        var (eidCol, nameCol, descCol) = ResolveColumns(worksheet);

        // 먼저 멤버들을 읽어 이름 최대 길이를 구한 뒤 '=' 정렬 폭을 정한다.
        var members = new List<(string Name, string Value, string? Desc)>();
        var lastRow = worksheet.LastRowUsed()?.RowNumber() ?? 0;
        for (var row = DataStartRow; row <= lastRow; row++)
        {
            var name = worksheet.Cell(row, nameCol).GetString().Trim();
            if (string.IsNullOrEmpty(name))
                continue;

            var value = worksheet.Cell(row, eidCol).GetString().Trim();
            var desc = descCol > 0 ? worksheet.Cell(row, descCol).GetString().Trim() : null;
            members.Add((name, value, string.IsNullOrEmpty(desc) ? null : desc));
        }

        // None/Max 센티널까지 포함해 '=' 정렬 폭을 계산한다.
        var nameWidth = members
            .Select(m => m.Name.Length)
            .Append("None".Length)
            .Append("Max".Length)
            .Max();

        sb.AppendLine($"public enum {worksheet.Name} : byte");
        sb.AppendLine("{");

        // 시작 센티널 None = 0
        sb.AppendLine($"    {"None".PadRight(nameWidth)} = 0,");
        sb.AppendLine();

        foreach (var (name, value, desc) in members)
        {
            var line = $"    {name.PadRight(nameWidth)} = {value},";
            if (desc is not null)
                line += $"  // {desc}";
            sb.AppendLine(line);
        }

        // 끝 센티널 Max (값 없이 자동)
        sb.AppendLine();
        sb.AppendLine($"    {"Max".PadRight(nameWidth)},");

        sb.AppendLine("};");
    }

    // 1행 헤더에서 EID/Name/Desc 컬럼 번호를 찾는다. 없으면 기본 위치(1/2/3)로 대체.
    private static (int eid, int name, int desc) ResolveColumns(IXLWorksheet worksheet)
    {
        int eid = 0, name = 0, desc = 0;
        var lastCol = worksheet.Row(HeaderRow).LastCellUsed()?.Address.ColumnNumber ?? 0;
        for (var col = 1; col <= lastCol; col++)
        {
            switch (worksheet.Cell(HeaderRow, col).GetString().Trim())
            {
                case "EID":  eid = col;  break;
                case "Name": name = col; break;
                case "Desc": desc = col; break;
            }
        }

        if (eid == 0) eid = 1;
        if (name == 0) name = 2;
        // Desc는 선택 컬럼이므로 못 찾으면 0(없음)으로 둔다.
        return (eid, name, desc);
    }

    // 생성된 enum 소스를 outputPath 디렉터리에 Enum.cs 파일로 쓴다.
    public static void MakeEnumCode(string outputPath)
    {
        if (null == _enumSource)
        {
            throw new Exception("Enum 소스가 생성되지 않아서 null 입니다. GenerateEnumSource 먼저 호출하세요.");
        }

        // outputPath는 파일 경로다. 부모 디렉터리만 생성하고, 파일은 WriteAllText가 덮어쓴다.
        var dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        var header =
            "// <auto-generated>\n" +
            "// 이 파일은 ExcelGenerator가 Excel(Enum.xlsx)로부터 생성했습니다. 직접 수정 금지.\n" +
            "// </auto-generated>\n\n";

        File.WriteAllText(outputPath, header + _enumSource, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }
}
