using System.Text;

namespace ExcelGenerator;

/// <summary>
/// 파싱된 TableData로부터 테이블 코드를 생성한다.
/// - Tables/{Table}.cs        : [MemoryPackable] Row 클래스 — 추후 서버/Unity 공유 대상 (MemoryPack 외 의존성 없음)
/// - Packer/{Table}Packer.cs  : 셀 문자열 → 강타입 Row 변환 + 직렬화/검증 — 툴 전용(배포 대상 아님)
/// - Packer/TableRegistry.cs  : 테이블명 → 패커 델리게이트 매핑
/// - Packer/PackerUtil.cs     : 공용 셀 파싱/검증 헬퍼 (고정 내용)
/// 생성 산출물은 이 프로젝트에서 컴파일하지 않으며(csproj Compile Remove),
/// GenerateData가 런타임에 인메모리 컴파일(TableCompiler)해 .bytes를 만든다 — 컴파일 성공 자체가 생성 코드 검증이다.
/// </summary>
public static class TableCodeGenerator
{
    private const string Header =
        "// <auto-generated>\n" +
        "// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.\n" +
        "// </auto-generated>\n\n";

    private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

    /// <summary>
    /// 모든 테이블의 코드를 outputDir 아래(Tables/, Packer/)에 생성한다.
    /// target: 포함할 플랫폼 필터 — 지금은 ServerClient(전체)로 호출하고,
    /// 추후 Client/Server 분리 출력이 필요하면 호출부에서 확장한다.
    /// (분리 도입 시 Row 필드 구성이 달라져 바이너리 호환이 깨지므로 전체 재생성 필수)
    /// </summary>
    public static void Generate(
        IReadOnlyList<ExcelGenerator.TableData> tables,
        string gameDataDir,
        string packerDir,
        ExcelGenerator.ColumnInfo.Platform target)
    {
        // 공유(서버·Unity 미러링) 산출물 = GameData 프로젝트 / 툴 전용 산출물 = Packer 폴더.
        var tablesDir = Path.Combine(gameDataDir, "Tables");

        // 삭제된 테이블의 생성물이 남지 않도록 Row/Packer 폴더는 매번 비운다.
        // gameDataDir 루트는 Enum.cs·GameData.csproj가 있으므로 통째로 비우지 않고 파일명 단위로 덮어쓴다.
        CleanDirectory(tablesDir);
        CleanDirectory(packerDir);

        var metas = new List<TableMeta>();
        foreach (var table in tables)
        {
            var columns = FilterColumns(table, target);

            File.WriteAllText(Path.Combine(tablesDir, $"{table.Name}.cs"),
                Header + BuildRowClass(table.Name, columns), Utf8NoBom);
            File.WriteAllText(Path.Combine(packerDir, $"{table.Name}Packer.cs"),
                Header + BuildPacker(table.Name, columns), Utf8NoBom);

            var key = PickKey(columns);
            metas.Add(new TableMeta(table.Name, key));

            var keyDesc = key is null ? "키 없음(리스트)" : $"키 {key.Value.Name}:{key.Value.Type}";
            Console.WriteLine($"[코드 생성] {table.Name}: 컬럼 {columns.Count}개, {keyDesc} → GameData/Tables/{table.Name}.cs, Packer/{table.Name}Packer.cs");
        }

        // 패커 전용(GenerateData가 런타임 컴파일할 때만 사용 — 배포 대상 아님)
        File.WriteAllText(Path.Combine(packerDir, "TableRegistry.cs"),
            Header + BuildRegistry(tables), Utf8NoBom);
        File.WriteAllText(Path.Combine(packerDir, "PackerUtil.cs"),
            Header + CodeGenUtil.BuildFile("GameData", PackerUtilUsings, PackerUtilBody), Utf8NoBom);

        // 공유(서버·Unity) 로드/조회 진입점 + 헬퍼
        File.WriteAllText(Path.Combine(gameDataDir, "GameTable.cs"),
            Header + BuildGameTable(metas), Utf8NoBom);
        File.WriteAllText(Path.Combine(gameDataDir, "TableSet.cs"),
            Header + CodeGenUtil.BuildFile("GameData", TableSetUsings, TableSetBody), Utf8NoBom);
    }

    /// <summary>GameTable 생성에 필요한 테이블 요약. Key가 null이면 리스트 전용 접근자로 생성한다.</summary>
    private readonly record struct TableMeta(string Name, (string Name, string Type)? Key);

    /// <summary>테이블 PK 컬럼을 고른다. ID 타입 컬럼 우선, 없으면 첫 비배열 컬럼. 배열뿐이면 키 없음.</summary>
    private static (string Name, string Type)? PickKey(List<(int CellIndex, ExcelGenerator.ColumnInfo Col)> columns)
    {
        var candidates = columns.Where(c => !IsArray(c.Col.Type)).ToList();
        if (candidates.Count == 0)
            return null;

        var chosen = candidates.FirstOrDefault(c => c.Col.Type == ExcelGenerator.ColumnInfo.RecordType.ID);
        if (chosen.Col is null)   // ID 타입 없음 → 첫 비배열 컬럼
            chosen = candidates[0];

        return (chosen.Col.Name, CSharpType(chosen.Col));
    }

    private static void CleanDirectory(string dir)
    {
        Directory.CreateDirectory(dir);
        foreach (var file in Directory.EnumerateFiles(dir, "*.cs"))
            File.Delete(file);
    }

    /// <summary>
    /// 코드에 포함할 컬럼만 고른다. CellIndex는 ParseSheet가 만든 셀 배열(columnInfos 순서)의 인덱스로,
    /// 생성 시점에 상수로 박혀 Ignore 컬럼 제외로 인한 인덱스 어긋남이 생기지 않는다.
    /// </summary>
    private static List<(int CellIndex, ExcelGenerator.ColumnInfo Col)> FilterColumns(
        ExcelGenerator.TableData table,
        ExcelGenerator.ColumnInfo.Platform target)
    {
        var result = new List<(int, ExcelGenerator.ColumnInfo)>();
        for (var i = 0; i < table.columnInfos.Count; i++)
        {
            var col = table.columnInfos[i];
            if (col.Type == ExcelGenerator.ColumnInfo.RecordType.Ignore)
            {
                // Type 행 오타가 조용히 사라지지 않도록 반드시 경고를 남긴다.
                Console.WriteLine($"[경고] {table.Name}.{col.Name}: 타입 '{col.RawType}' 미인식/미지원 → 코드·데이터에서 제외 (Time 등은 추후 지원 예정)");
                continue;
            }
            if ((col.CS & target) == 0)
                continue;   // 대상 플랫폼에 포함되지 않는 컬럼

            result.Add((i, col));
        }
        return result;
    }

    // ─────────────────────────── Row 클래스 ───────────────────────────

    private static string BuildRowClass(string tableName, List<(int CellIndex, ExcelGenerator.ColumnInfo Col)> columns)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"/// <summary>{tableName} 테이블의 한 행. {tableName}.bytes = MemoryPackSerializer.Serialize(List&lt;{tableName}Row&gt;)</summary>");
        sb.AppendLine("[MemoryPackable]");
        sb.AppendLine($"public partial class {tableName}Row");
        sb.AppendLine("{");

        // 본문을 먼저 만들고 최대 길이에 맞춰 주석('// 원본 타입')을 정렬한다.
        var typeWidth = columns.Max(c => CSharpType(c.Col).Length);
        var nameWidth = columns.Max(c => c.Col.Name.Length);
        var bodies = columns.Select(c =>
        {
            var type = CSharpType(c.Col);
            var init = c.Col.Type switch
            {
                ExcelGenerator.ColumnInfo.RecordType.String => " = \"\";",
                // 배열은 null 대신 빈 배열로 초기화. Unity(C# 9)로 미러링되므로 컬렉션 표현식 []([C#12) 대신 Array.Empty 사용.
                _ when IsArray(c.Col.Type)                  => $" = System.Array.Empty<{ElementType(c.Col)}>();",
                _                                           => "",
            };
            return (Body: $"    public {type.PadRight(typeWidth)} {c.Col.Name.PadRight(nameWidth)} {{ get; set; }}{init}",
                    Comment: BuildColumnComment(c.Col));
        }).ToList();

        var bodyWidth = bodies.Max(b => b.Body.Length);
        foreach (var (body, comment) in bodies)
            sb.AppendLine($"{body.PadRight(bodyWidth)}  // {comment}");

        sb.AppendLine("}");
        return CodeGenUtil.BuildFile("GameData", new[] { "MemoryPack" }, sb.ToString());
    }

    /// <summary>
    /// 기획자가 시트에 메모를 남기는 예약 컬럼명.
    /// 이 컬럼은 <b>게임 로직에 아무 영향을 주지 않는다</b> — 사람이 읽는 설명일 뿐이다.
    /// 값을 바꿔도, 비워도 동작이 달라지지 않으므로 코드에서 참조하지 않는다.
    /// </summary>
    private const string MemoColumnName = "Description";

    /// <summary>프로퍼티 뒤에 붙는 주석: 원본 타입 + 범위/기본값 정보.</summary>
    private static string BuildColumnComment(ExcelGenerator.ColumnInfo col)
    {
        var comment = col.RawType;
        if (col.Min is not null || col.Max is not null)
            comment += $" [{col.Min?.ToString() ?? "-"}..{col.Max?.ToString() ?? "-"}]";
        if (col.DefaultValue is not null)
            comment += $" 기본={col.DefaultValue}";

        // 메모 컬럼임을 생성물에 남긴다. 이 주석이 없으면 다음 사람이 로직에서 끌어다 쓴다.
        if (string.Equals(col.Name, MemoColumnName, StringComparison.Ordinal))
            comment += " [기획 메모 — 로직에서 읽지 않는다]";

        return comment;
    }

    // ─────────────────────────── Packer ───────────────────────────

    private static string BuildPacker(string tableName, List<(int CellIndex, ExcelGenerator.ColumnInfo Col)> columns)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"/// <summary>{tableName} 시트의 셀 문자열을 {tableName}Row로 변환하고 MemoryPack으로 직렬화한다. (패커 전용 — 클라/서버 배포 대상 아님)</summary>");
        sb.AppendLine($"public static class {tableName}Packer");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string Table = \"{tableName}\";");
        sb.AppendLine();

        // Parse: 셀 인덱스는 생성 시점에 고정된 상수
        sb.AppendLine("    /// <summary>셀 배열(파싱된 컬럼 순서)을 강타입 Row로 변환한다.</summary>");
        sb.AppendLine($"    public static {tableName}Row Parse(string[] cells) => new()");
        sb.AppendLine("    {");
        var nameWidth = columns.Max(c => c.Col.Name.Length);
        foreach (var (cellIndex, col) in columns)
            sb.AppendLine($"        {col.Name.PadRight(nameWidth)} = {BuildParseExpression(col, cellIndex)},");
        sb.AppendLine("    };");
        sb.AppendLine();

        sb.AppendLine($$"""
    /// <summary>모든 행을 파싱해 MemoryPack 바이너리로 직렬화한다. 실패 시 행 번호를 포함해 예외를 던진다.</summary>
    public static byte[] Pack(IReadOnlyList<string[]> rows)
    {
        var list = new List<{{tableName}}Row>(rows.Count);
        for (var i = 0; i < rows.Count; i++)
        {
            try { list.Add(Parse(rows[i])); }
            catch (Exception ex)
            {
                throw new InvalidDataException($"[{Table}] 데이터 {i + 1}번째 행 파싱 실패", ex);
            }
        }
        return MemoryPackSerializer.Serialize(list);
    }

    /// <summary>바이너리를 역직렬화해 행 수를 확인하고, 재직렬화 결과가 원본과 같은지 검증한다(라운드트립).</summary>
    public static int Verify(byte[] bytes)
    {
        var list = MemoryPackSerializer.Deserialize<List<{{tableName}}Row>>(bytes)
                   ?? throw new InvalidDataException($"[{Table}] 역직렬화 결과가 null입니다.");
        var again = MemoryPackSerializer.Serialize(list);
        if (!again.AsSpan().SequenceEqual(bytes))
            throw new InvalidDataException($"[{Table}] 재직렬화 바이트가 원본과 다릅니다.");
        return list.Count;
    }

    /// <summary>첫 행을 사람이 읽을 수 있는 형태로 덤프한다(콘솔 검증용).</summary>
    public static string Preview(byte[] bytes)
    {
        var list = MemoryPackSerializer.Deserialize<List<{{tableName}}Row>>(bytes);
        return list is { Count: > 0 }
            ? System.Text.Json.JsonSerializer.Serialize(list[0])
            : "(빈 테이블)";
    }

    /// <summary>모든 행을 사람이 읽을 JSON으로 덤프한다(enum=이름, 들여쓰기, 한글 그대로). 엑셀 대조/리뷰용 사이드카.</summary>
    public static string Dump(byte[] bytes)
    {
        var list = MemoryPackSerializer.Deserialize<List<{{tableName}}Row>>(bytes) ?? new();
        var options = new System.Text.Json.JsonSerializerOptions
        {
            WriteIndented = true,
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        };
        options.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
        return System.Text.Json.JsonSerializer.Serialize(list, options);
    }
}
""");
        return CodeGenUtil.BuildFile("GameData", new[] { "MemoryPack" }, sb.ToString());
    }

    /// <summary>컬럼 하나의 "셀 문자열 → 값" 변환 식을 만든다. 빈 셀은 Default가 있으면 리터럴로 대체, 없으면 헬퍼가 예외를 던진다(fail-fast).</summary>
    private static string BuildParseExpression(ExcelGenerator.ColumnInfo col, int cellIndex)
    {
        var cell = $"cells[{cellIndex}]";
        var core = BuildCoreExpression(col, cell);

        if (col.DefaultValue is null)
            return core;

        return $"{cell}.Length > 0 ? {core} : {BuildDefaultLiteral(col)}";
    }

    private static string BuildCoreExpression(ExcelGenerator.ColumnInfo col, string cell)
    {
        // Min/Max가 있으면 헬퍼의 범위 검증 인자를 함께 방출한다.
        var range = col.Min is not null || col.Max is not null
            ? $", {col.Min?.ToString() ?? "null"}, {col.Max?.ToString() ?? "null"}"
            : "";

        return col.Type switch
        {
            ExcelGenerator.ColumnInfo.RecordType.Int      => $"PackerUtil.ParseInt({cell}, Table, \"{col.Name}\"{range})",
            ExcelGenerator.ColumnInfo.RecordType.ID       => $"PackerUtil.ParseInt({cell}, Table, \"{col.Name}\"{range})",
            ExcelGenerator.ColumnInfo.RecordType.Long     => $"PackerUtil.ParseLong({cell}, Table, \"{col.Name}\"{range})",
            ExcelGenerator.ColumnInfo.RecordType.Float    => $"PackerUtil.ParseFloat({cell}, Table, \"{col.Name}\"{range})",
            ExcelGenerator.ColumnInfo.RecordType.Bool     => $"PackerUtil.ParseBool({cell}, Table, \"{col.Name}\")",
            ExcelGenerator.ColumnInfo.RecordType.String   => $"PackerUtil.RequireString({cell}, Table, \"{col.Name}\")",
            ExcelGenerator.ColumnInfo.RecordType.EnumType => $"PackerUtil.ParseEnum<{CSharpType(col)}>({cell}, Table, \"{col.Name}\")",

            // 배열: 빈 셀 → 빈 배열, ',' 구분. 정수 배열은 원본 타입(int/long)으로 헬퍼를 나눈다.
            ExcelGenerator.ColumnInfo.RecordType.ArrayNumber => ElementType(col) == "long"
                ? $"PackerUtil.ParseLongArray({cell}, Table, \"{col.Name}\"{range})"
                : $"PackerUtil.ParseIntArray({cell}, Table, \"{col.Name}\"{range})",
            ExcelGenerator.ColumnInfo.RecordType.ArrayFloat  => $"PackerUtil.ParseFloatArray({cell}, Table, \"{col.Name}\"{range})",
            ExcelGenerator.ColumnInfo.RecordType.ArrayString => $"PackerUtil.ParseStringArray({cell}, Table, \"{col.Name}\")",
            ExcelGenerator.ColumnInfo.RecordType.ArrayEnum   => $"PackerUtil.ParseEnumArray<{ElementType(col)}>({cell}, Table, \"{col.Name}\")",

            _ => throw new NotSupportedException($"{col.Name}: RecordType.{col.Type}는 코드 생성 미지원"),
        };
    }

    /// <summary>Default(Null) 셀 값을 타입에 맞는 C# 리터럴로 바꾼다.</summary>
    private static string BuildDefaultLiteral(ExcelGenerator.ColumnInfo col)
    {
        if (IsArray(col.Type))
            return BuildArrayDefaultLiteral(col);

        var d = col.DefaultValue!;
        return col.Type switch
        {
            ExcelGenerator.ColumnInfo.RecordType.Float    => d.EndsWith("f") ? d : d + "f",
            ExcelGenerator.ColumnInfo.RecordType.Bool     => d.ToLowerInvariant(),
            ExcelGenerator.ColumnInfo.RecordType.String   => BuildStringDefaultLiteral(d),
            ExcelGenerator.ColumnInfo.RecordType.EnumType => $"{CSharpType(col)}.{d}",
            _                                             => d,   // Int/ID/Long
        };
    }

    /// <summary>
    /// string 컬럼의 Default(Null)을 C# 리터럴로 바꾼다.
    ///
    /// Default(Null) 셀 자체가 비어 있으면 "기본값 없음"(= 빈 데이터 셀은 오류)으로 읽히므로,
    /// **빈 문자열을 기본값으로 두고 싶다는 의도**를 표현할 방법이 없었다.
    /// 설명·비고처럼 비워 두는 게 정상인 컬럼을 위해 <c>""</c>(따옴표 두 개)를 그 표기로 정한다.
    /// 이렇게 두면 "빈 셀은 오류"라는 fail-fast 기본값은 그대로 유지된다.
    /// </summary>
    private static string BuildStringDefaultLiteral(string d)
    {
        if (d is "\"\"" or "''")
            return "\"\"";

        return $"\"{d.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
    }

    /// <summary>배열 컬럼의 Default(Null)을 "new T[]{ ... }" 리터럴로 바꾼다. ',' 구분, 빈 토큰 제외.</summary>
    private static string BuildArrayDefaultLiteral(ExcelGenerator.ColumnInfo col)
    {
        var element = ElementType(col);
        var items = col.DefaultValue!
            .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(v => FormatElementLiteral(col.Type, element, v));
        return $"new {CSharpType(col)} {{ {string.Join(", ", items)} }}";
    }

    /// <summary>배열 원소 하나를 C# 리터럴로 포맷한다(스칼라 규칙 재사용).</summary>
    private static string FormatElementLiteral(ExcelGenerator.ColumnInfo.RecordType arrayType, string element, string value) => arrayType switch
    {
        ExcelGenerator.ColumnInfo.RecordType.ArrayFloat  => value.EndsWith("f") ? value : value + "f",
        ExcelGenerator.ColumnInfo.RecordType.ArrayString => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"",
        ExcelGenerator.ColumnInfo.RecordType.ArrayEnum   => $"{element}.{value}",
        _                                                => value,   // ArrayNumber(int/long)
    };

    /// <summary>RecordType → C# 타입. enum은 e접두사를 벗겨 Enum.xlsx 시트명과 매칭한다(eItemType → ItemType).</summary>
    private static string CSharpType(ExcelGenerator.ColumnInfo col) => col.Type switch
    {
        ExcelGenerator.ColumnInfo.RecordType.Int      => "int",
        ExcelGenerator.ColumnInfo.RecordType.Long     => "long",
        ExcelGenerator.ColumnInfo.RecordType.Float    => "float",
        ExcelGenerator.ColumnInfo.RecordType.String   => "string",
        ExcelGenerator.ColumnInfo.RecordType.Bool     => "bool",
        ExcelGenerator.ColumnInfo.RecordType.ID       => "int",
        ExcelGenerator.ColumnInfo.RecordType.EnumType => col.RawType[1..],
        // 배열: int[]/long[]/float[]/string[]은 원본 표기가 그대로 유효, enum만 e접두사 제거(eItemType[] → ItemType[]).
        ExcelGenerator.ColumnInfo.RecordType.ArrayNumber => col.RawType,
        ExcelGenerator.ColumnInfo.RecordType.ArrayFloat  => col.RawType,
        ExcelGenerator.ColumnInfo.RecordType.ArrayString => col.RawType,
        ExcelGenerator.ColumnInfo.RecordType.ArrayEnum   => col.RawType[1..],
        _ => throw new NotSupportedException($"{col.Name}: RecordType.{col.Type}는 코드 생성 미지원"),
    };

    /// <summary>배열 컬럼의 원소 C# 타입(끝의 "[]" 제거). int[]→int, eItemType[]→ItemType</summary>
    private static string ElementType(ExcelGenerator.ColumnInfo col)
    {
        var cs = CSharpType(col);
        return cs.EndsWith("[]") ? cs[..^2] : cs;
    }

    /// <summary>Array 계열 RecordType 여부.</summary>
    private static bool IsArray(ExcelGenerator.ColumnInfo.RecordType t) =>
        t is ExcelGenerator.ColumnInfo.RecordType.ArrayString
          or ExcelGenerator.ColumnInfo.RecordType.ArrayNumber
          or ExcelGenerator.ColumnInfo.RecordType.ArrayFloat
          or ExcelGenerator.ColumnInfo.RecordType.ArrayEnum;

    // ─────────────────────────── TableRegistry ───────────────────────────

    private static string BuildRegistry(IReadOnlyList<ExcelGenerator.TableData> tables)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/// <summary>테이블명 → 패커 델리게이트. GenerateData가 시트명으로 조회해 .bytes를 만든다.</summary>");
        sb.AppendLine("public static class TableRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Pack: 셀 행들 → 바이너리 / Verify: 라운드트립 검증(행 수 반환) / Preview: 첫 행 / Dump: 전체 행 JSON(리뷰용)</summary>");
        sb.AppendLine("    public sealed record Entry(");
        sb.AppendLine("        Func<IReadOnlyList<string[]>, byte[]> Pack,");
        sb.AppendLine("        Func<byte[], int>                     Verify,");
        sb.AppendLine("        Func<byte[], string>                  Preview,");
        sb.AppendLine("        Func<byte[], string>                  Dump);");
        sb.AppendLine();
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, Entry> Tables = new Dictionary<string, Entry>");
        sb.AppendLine("    {");
        foreach (var table in tables)
            sb.AppendLine($"        [\"{table.Name}\"] = new({table.Name}Packer.Pack, {table.Name}Packer.Verify, {table.Name}Packer.Preview, {table.Name}Packer.Dump),");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return CodeGenUtil.BuildFile("GameData", Array.Empty<string>(), sb.ToString());
    }

    // ─────────────────────────── GameTable (공유 접근자) ───────────────────────────

    /// <summary>테이블별 로드/조회 진입점을 생성한다. 키가 있으면 TableSet, 없으면 리스트로 노출한다.</summary>
    private static string BuildGameTable(IReadOnlyList<TableMeta> metas)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/// <summary>모든 데이터 테이블의 로드/조회 진입점. LoadAll에 파일 읽기 델리게이트를 주입한다(서버=File, Unity=StreamingAssets).</summary>");
        sb.AppendLine("public static class GameTable");
        sb.AppendLine("{");

        foreach (var m in metas)
        {
            if (m.Key is not null)
                sb.AppendLine($"    public static TableSet<{m.Key.Value.Type}, {m.Name}Row> {m.Name} {{ get; private set; }} = null!;");
            else
                sb.AppendLine($"    public static IReadOnlyList<{m.Name}Row> {m.Name} {{ get; private set; }} = Array.Empty<{m.Name}Row>();");
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>read: \"테이블명.bytes\" → 바이트. 모든 테이블을 로드/인덱싱한다.</summary>");
        sb.AppendLine("    public static void LoadAll(Func<string, byte[]> read)");
        sb.AppendLine("    {");
        foreach (var m in metas)
        {
            if (m.Key is not null)
                sb.AppendLine($"        {m.Name} = TableSet<{m.Key.Value.Type}, {m.Name}Row>.From(read(\"{m.Name}.bytes\"), r => r.{m.Key.Value.Name});");
            else
                sb.AppendLine($"        {m.Name} = MemoryPackSerializer.Deserialize<List<{m.Name}Row>>(read(\"{m.Name}.bytes\")) ?? new List<{m.Name}Row>();");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return CodeGenUtil.BuildFile(
            "GameData",
            new[] { "System", "System.Collections.Generic", "MemoryPack" },
            sb.ToString());
    }

    // ─────────────────────────── TableSet (고정 소스, 서버·Unity 공유) ───────────────────────────
    // Unity(C# 9 / netstandard2.1)에서도 컴파일되도록 컬렉션 표현식·기본 인터페이스 멤버 등 신문법을 쓰지 않는다.
    // using·namespace는 CodeGenUtil.BuildFile이 붙인다(본문만 보관).
    private static readonly string[] TableSetUsings = { "System", "System.Collections.Generic", "MemoryPack" };

    private const string TableSetBody = """
/// <summary>키 → Row 매핑 테이블. .bytes를 역직렬화해 인덱싱하며, 로드 후 불변으로 사용한다.</summary>
public sealed class TableSet<TKey, TRow> where TKey : notnull
{
    private readonly Dictionary<TKey, TRow> _byKey;

    /// <summary>원본(엑셀) 순서를 유지한 전체 행.</summary>
    public IReadOnlyList<TRow> All { get; }

    public int Count => All.Count;

    private TableSet(IReadOnlyList<TRow> all, Dictionary<TKey, TRow> byKey)
    {
        All = all;
        _byKey = byKey;
    }

    /// <summary>키로 조회한다. 없으면 예외(데이터 참조 버그를 조용히 넘기지 않는다).</summary>
    public TRow this[TKey key]
        => _byKey.TryGetValue(key, out var row)
            ? row
            : throw new KeyNotFoundException($"[{typeof(TRow).Name}] 키 '{key}'를 찾을 수 없습니다.");

    public bool TryGet(TKey key, out TRow row) => _byKey.TryGetValue(key, out row!);

    public bool Contains(TKey key) => _byKey.ContainsKey(key);

    /// <summary>MemoryPack 바이트를 역직렬화하고 keySelector로 키를 뽑아 인덱싱한다. 키 중복 시 예외.</summary>
    public static TableSet<TKey, TRow> From(byte[] bytes, Func<TRow, TKey> keySelector)
    {
        var all = MemoryPackSerializer.Deserialize<List<TRow>>(bytes)
                  ?? throw new InvalidOperationException($"[{typeof(TRow).Name}] 역직렬화 결과가 null입니다.");

        var byKey = new Dictionary<TKey, TRow>(all.Count);
        foreach (var row in all)
        {
            var key = keySelector(row);
            if (!byKey.TryAdd(key, row))
                throw new InvalidOperationException($"[{typeof(TRow).Name}] 키 '{key}'가 중복됩니다.");
        }
        return new TableSet<TKey, TRow>(all, byKey);
    }
}
""";

    // ─────────────────────────── PackerUtil (고정 소스) ───────────────────────────
    // using·namespace는 CodeGenUtil.BuildFile이 붙인다(본문만 보관).
    private static readonly string[] PackerUtilUsings = { "System.Globalization" };

    private const string PackerUtilBody = """
/// <summary>
/// 생성된 Packer들이 공용으로 쓰는 셀 파싱/검증 헬퍼.
/// 실패 시 테이블/컬럼명을 포함해 즉시 예외를 던진다(fail-fast) — 조용한 기본값 주입은 데이터 버그를 숨긴다.
/// </summary>
public static class PackerUtil
{
    public static int ParseInt(string cell, string table, string column, int? min = null, int? max = null)
    {
        if (cell.Length == 0)
            throw Empty(table, column);
        if (!int.TryParse(cell, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))
            throw Invalid(table, column, "int", cell);
        CheckRange(v, min, max, table, column);
        return v;
    }

    public static long ParseLong(string cell, string table, string column, int? min = null, int? max = null)
    {
        if (cell.Length == 0)
            throw Empty(table, column);
        if (!long.TryParse(cell, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))
            throw Invalid(table, column, "long", cell);
        CheckRange(v, min, max, table, column);
        return v;
    }

    public static float ParseFloat(string cell, string table, string column, int? min = null, int? max = null)
    {
        if (cell.Length == 0)
            throw Empty(table, column);
        if (!float.TryParse(cell, NumberStyles.Float, CultureInfo.InvariantCulture, out var v))
            throw Invalid(table, column, "float", cell);
        CheckRange(v, min, max, table, column);
        return v;
    }

    public static bool ParseBool(string cell, string table, string column)
    {
        if (cell.Length == 0)
            throw Empty(table, column);
        if (!bool.TryParse(cell, out var v))
            throw Invalid(table, column, "bool", cell);
        return v;
    }

    public static string RequireString(string cell, string table, string column)
        => cell.Length > 0 ? cell : throw Empty(table, column);

    // ─── 배열: ',' 구분, 빈 셀 → 빈 배열. 원소는 스칼라 파서를 재사용해 범위·형식 검증을 그대로 적용한다. ───

    public static int[] ParseIntArray(string cell, string table, string column, int? min = null, int? max = null)
        => SplitCells(cell).Select(c => ParseInt(c, table, column, min, max)).ToArray();

    public static long[] ParseLongArray(string cell, string table, string column, int? min = null, int? max = null)
        => SplitCells(cell).Select(c => ParseLong(c, table, column, min, max)).ToArray();

    public static float[] ParseFloatArray(string cell, string table, string column, int? min = null, int? max = null)
        => SplitCells(cell).Select(c => ParseFloat(c, table, column, min, max)).ToArray();

    public static string[] ParseStringArray(string cell, string table, string column)
        => SplitCells(cell).ToArray();

    public static TEnum[] ParseEnumArray<TEnum>(string cell, string table, string column) where TEnum : struct, Enum
        => SplitCells(cell).Select(c => ParseEnum<TEnum>(c, table, column)).ToArray();

    /// <summary>배열 셀을 ','로 분리하고 각 토큰을 트리밍한다. 빈 셀·빈 토큰은 제외(빈 셀 → 빈 배열).</summary>
    private static string[] SplitCells(string cell)
        => cell.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

    public static TEnum ParseEnum<TEnum>(string cell, string table, string column) where TEnum : struct, Enum
    {
        if (cell.Length == 0)
            throw Empty(table, column);
        if (!Enum.TryParse<TEnum>(cell, out var v) || !Enum.IsDefined(v))
            throw Invalid(table, column, typeof(TEnum).Name, cell);
        return v;
    }

    private static void CheckRange(double v, int? min, int? max, string table, string column)
    {
        // nullable 비교: min/max가 null이면 조건이 false가 되어 통과한다.
        if (v < min || v > max)
            throw new InvalidDataException($"[{table}.{column}] 값 {v}이(가) 범위 [{min?.ToString() ?? "-"}..{max?.ToString() ?? "-"}]를 벗어났습니다.");
    }

    private static Exception Empty(string table, string column)
        => new InvalidDataException($"[{table}.{column}] 셀이 비었는데 Default(Null) 값이 없습니다.");

    private static Exception Invalid(string table, string column, string type, string cell)
        => new InvalidDataException($"[{table}.{column}] {type} 파싱 실패: '{cell}'");
}
""";
}
