// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using System;
using System.Collections.Generic;
using MemoryPack;

namespace GameData
{
    /// <summary>모든 데이터 테이블의 로드/조회 진입점. LoadAll에 파일 읽기 델리게이트를 주입한다(서버=File, Unity=StreamingAssets).</summary>
    public static class GameTable
    {
        public static TableSet<int, CharacterTableRow> CharacterTable { get; private set; } = null!;
        public static TableSet<int, WorkSpeedTableRow> WorkSpeedTable { get; private set; } = null!;
        public static TableSet<int, FishingBasicTableRow> FishingBasicTable { get; private set; } = null!;
        public static TableSet<int, FarmingBasicTableRow> FarmingBasicTable { get; private set; } = null!;
        public static TableSet<int, LoggingBasicTableRow> LoggingBasicTable { get; private set; } = null!;
        public static TableSet<int, MiningBasicTableRow> MiningBasicTable { get; private set; } = null!;
        public static TableSet<int, HuntingBasicTableRow> HuntingBasicTable { get; private set; } = null!;
        public static TableSet<int, GachaTableRow> GachaTable { get; private set; } = null!;
        public static TableSet<int, IndustryLevelTableRow> IndustryLevelTable { get; private set; } = null!;
        public static TableSet<int, ItemTableRow> ItemTable { get; private set; } = null!;

        /// <summary>read: "테이블명.bytes" → 바이트. 모든 테이블을 로드/인덱싱한다.</summary>
        public static void LoadAll(Func<string, byte[]> read)
        {
            CharacterTable = TableSet<int, CharacterTableRow>.From(read("CharacterTable.bytes"), r => r.CharacterTID);
            WorkSpeedTable = TableSet<int, WorkSpeedTableRow>.From(read("WorkSpeedTable.bytes"), r => r.WorkSpeedTID);
            FishingBasicTable = TableSet<int, FishingBasicTableRow>.From(read("FishingBasicTable.bytes"), r => r.DropTID);
            FarmingBasicTable = TableSet<int, FarmingBasicTableRow>.From(read("FarmingBasicTable.bytes"), r => r.DropTID);
            LoggingBasicTable = TableSet<int, LoggingBasicTableRow>.From(read("LoggingBasicTable.bytes"), r => r.DropTID);
            MiningBasicTable = TableSet<int, MiningBasicTableRow>.From(read("MiningBasicTable.bytes"), r => r.DropTID);
            HuntingBasicTable = TableSet<int, HuntingBasicTableRow>.From(read("HuntingBasicTable.bytes"), r => r.DropTID);
            GachaTable = TableSet<int, GachaTableRow>.From(read("GachaTable.bytes"), r => r.GachaTID);
            IndustryLevelTable = TableSet<int, IndustryLevelTableRow>.From(read("IndustryLevelTable.bytes"), r => r.IndustryLevelTID);
            ItemTable = TableSet<int, ItemTableRow>.From(read("ItemTable.bytes"), r => r.ItemTID);
        }
    }
}
