// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using System;
using System.Collections.Generic;
using MemoryPack;

namespace GameData
{
    /// <summary>키 → Row 매핑 테이블. .bytes를 역직렬화해 인덱싱하며, 로드 후 불변으로 사용한다.</summary>
    public sealed class TableSet<TKey, TRow> where TKey : notnull
    {
        private readonly Dictionary<TKey, TRow> _byKey;

        /// <summary>원본(엑셀) 순서를 유지한 전체 행.</summary>
        public IReadOnlyList<TRow> All { get; }

        public int Count => All.Count;

        private TableSet(IReadOnlyList<TRow> all, Dictionary<TKey, TRow> byKey)
        {
            All = all;
            _byKey = byKey;
        }

        /// <summary>키로 조회한다. 없으면 예외(데이터 참조 버그를 조용히 넘기지 않는다).</summary>
        public TRow this[TKey key]
            => _byKey.TryGetValue(key, out var row)
                ? row
                : throw new KeyNotFoundException($"[{typeof(TRow).Name}] 키 '{key}'를 찾을 수 없습니다.");

        public bool TryGet(TKey key, out TRow row) => _byKey.TryGetValue(key, out row!);

        public bool Contains(TKey key) => _byKey.ContainsKey(key);

        /// <summary>MemoryPack 바이트를 역직렬화하고 keySelector로 키를 뽑아 인덱싱한다. 키 중복 시 예외.</summary>
        public static TableSet<TKey, TRow> From(byte[] bytes, Func<TRow, TKey> keySelector)
        {
            var all = MemoryPackSerializer.Deserialize<List<TRow>>(bytes)
                      ?? throw new InvalidOperationException($"[{typeof(TRow).Name}] 역직렬화 결과가 null입니다.");

            var byKey = new Dictionary<TKey, TRow>(all.Count);
            foreach (var row in all)
            {
                var key = keySelector(row);
                if (!byKey.TryAdd(key, row))
                    throw new InvalidOperationException($"[{typeof(TRow).Name}] 키 '{key}'가 중복됩니다.");
            }
            return new TableSet<TKey, TRow>(all, byKey);
        }
    }
}
