// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>CharacterTable 테이블의 한 행. CharacterTable.bytes = MemoryPackSerializer.Serialize(List&lt;CharacterTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class CharacterTableRow
    {
        public int    CharacterTID { get; set; }        // int
        public string Name         { get; set; } = "";  // string
        public int    Farming      { get; set; }        // int
        public int    Fishing      { get; set; }        // int
        public int    Mining       { get; set; }        // int
        public int    Logging      { get; set; }        // int
        public int    Hunting      { get; set; }        // int
        public string Description  { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
