// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>FarmingBasicTable 시트의 셀 문자열을 FarmingBasicTableRow로 변환하고 MemoryPack으로 직렬화한다. (패커 전용 — 클라/서버 배포 대상 아님)</summary>
    public static class FarmingBasicTablePacker
    {
        private const string Table = "FarmingBasicTable";

        /// <summary>셀 배열(파싱된 컬럼 순서)을 강타입 Row로 변환한다.</summary>
        public static FarmingBasicTableRow Parse(string[] cells) => new()
        {
            DropTID       = PackerUtil.ParseInt(cells[0], Table, "DropTID"),
            IndustryLevel = PackerUtil.ParseInt(cells[1], Table, "IndustryLevel", 1, 5),
            ItemTID       = PackerUtil.ParseInt(cells[2], Table, "ItemTID"),
            Weight        = PackerUtil.ParseInt(cells[3], Table, "Weight"),
            Description   = cells[4].Length > 0 ? PackerUtil.RequireString(cells[4], Table, "Description") : "",
        };

        /// <summary>모든 행을 파싱해 MemoryPack 바이너리로 직렬화한다. 실패 시 행 번호를 포함해 예외를 던진다.</summary>
        public static byte[] Pack(IReadOnlyList<string[]> rows)
        {
            var list = new List<FarmingBasicTableRow>(rows.Count);
            for (var i = 0; i < rows.Count; i++)
            {
                try { list.Add(Parse(rows[i])); }
                catch (Exception ex)
                {
                    throw new InvalidDataException($"[{Table}] 데이터 {i + 1}번째 행 파싱 실패", ex);
                }
            }
            return MemoryPackSerializer.Serialize(list);
        }

        /// <summary>바이너리를 역직렬화해 행 수를 확인하고, 재직렬화 결과가 원본과 같은지 검증한다(라운드트립).</summary>
        public static int Verify(byte[] bytes)
        {
            var list = MemoryPackSerializer.Deserialize<List<FarmingBasicTableRow>>(bytes)
                       ?? throw new InvalidDataException($"[{Table}] 역직렬화 결과가 null입니다.");
            var again = MemoryPackSerializer.Serialize(list);
            if (!again.AsSpan().SequenceEqual(bytes))
                throw new InvalidDataException($"[{Table}] 재직렬화 바이트가 원본과 다릅니다.");
            return list.Count;
        }

        /// <summary>첫 행을 사람이 읽을 수 있는 형태로 덤프한다(콘솔 검증용).</summary>
        public static string Preview(byte[] bytes)
        {
            var list = MemoryPackSerializer.Deserialize<List<FarmingBasicTableRow>>(bytes);
            return list is { Count: > 0 }
                ? System.Text.Json.JsonSerializer.Serialize(list[0])
                : "(빈 테이블)";
        }

        /// <summary>모든 행을 사람이 읽을 JSON으로 덤프한다(enum=이름, 들여쓰기, 한글 그대로). 엑셀 대조/리뷰용 사이드카.</summary>
        public static string Dump(byte[] bytes)
        {
            var list = MemoryPackSerializer.Deserialize<List<FarmingBasicTableRow>>(bytes) ?? new();
            var options = new System.Text.Json.JsonSerializerOptions
            {
                WriteIndented = true,
                Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
            };
            options.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
            return System.Text.Json.JsonSerializer.Serialize(list, options);
        }
    }
}
