// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using System.Globalization;

namespace GameData
{
    /// <summary>
    /// 생성된 Packer들이 공용으로 쓰는 셀 파싱/검증 헬퍼.
    /// 실패 시 테이블/컬럼명을 포함해 즉시 예외를 던진다(fail-fast) — 조용한 기본값 주입은 데이터 버그를 숨긴다.
    /// </summary>
    public static class PackerUtil
    {
        public static int ParseInt(string cell, string table, string column, int? min = null, int? max = null)
        {
            if (cell.Length == 0)
                throw Empty(table, column);
            if (!int.TryParse(cell, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))
                throw Invalid(table, column, "int", cell);
            CheckRange(v, min, max, table, column);
            return v;
        }

        public static long ParseLong(string cell, string table, string column, int? min = null, int? max = null)
        {
            if (cell.Length == 0)
                throw Empty(table, column);
            if (!long.TryParse(cell, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))
                throw Invalid(table, column, "long", cell);
            CheckRange(v, min, max, table, column);
            return v;
        }

        public static float ParseFloat(string cell, string table, string column, int? min = null, int? max = null)
        {
            if (cell.Length == 0)
                throw Empty(table, column);
            if (!float.TryParse(cell, NumberStyles.Float, CultureInfo.InvariantCulture, out var v))
                throw Invalid(table, column, "float", cell);
            CheckRange(v, min, max, table, column);
            return v;
        }

        public static bool ParseBool(string cell, string table, string column)
        {
            if (cell.Length == 0)
                throw Empty(table, column);
            if (!bool.TryParse(cell, out var v))
                throw Invalid(table, column, "bool", cell);
            return v;
        }

        public static string RequireString(string cell, string table, string column)
            => cell.Length > 0 ? cell : throw Empty(table, column);

        // ─── 배열: ',' 구분, 빈 셀 → 빈 배열. 원소는 스칼라 파서를 재사용해 범위·형식 검증을 그대로 적용한다. ───

        public static int[] ParseIntArray(string cell, string table, string column, int? min = null, int? max = null)
            => SplitCells(cell).Select(c => ParseInt(c, table, column, min, max)).ToArray();

        public static long[] ParseLongArray(string cell, string table, string column, int? min = null, int? max = null)
            => SplitCells(cell).Select(c => ParseLong(c, table, column, min, max)).ToArray();

        public static float[] ParseFloatArray(string cell, string table, string column, int? min = null, int? max = null)
            => SplitCells(cell).Select(c => ParseFloat(c, table, column, min, max)).ToArray();

        public static string[] ParseStringArray(string cell, string table, string column)
            => SplitCells(cell).ToArray();

        public static TEnum[] ParseEnumArray<TEnum>(string cell, string table, string column) where TEnum : struct, Enum
            => SplitCells(cell).Select(c => ParseEnum<TEnum>(c, table, column)).ToArray();

        /// <summary>배열 셀을 ','로 분리하고 각 토큰을 트리밍한다. 빈 셀·빈 토큰은 제외(빈 셀 → 빈 배열).</summary>
        private static string[] SplitCells(string cell)
            => cell.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        public static TEnum ParseEnum<TEnum>(string cell, string table, string column) where TEnum : struct, Enum
        {
            if (cell.Length == 0)
                throw Empty(table, column);
            if (!Enum.TryParse<TEnum>(cell, out var v) || !Enum.IsDefined(v))
                throw Invalid(table, column, typeof(TEnum).Name, cell);
            return v;
        }

        private static void CheckRange(double v, int? min, int? max, string table, string column)
        {
            // nullable 비교: min/max가 null이면 조건이 false가 되어 통과한다.
            if (v < min || v > max)
                throw new InvalidDataException($"[{table}.{column}] 값 {v}이(가) 범위 [{min?.ToString() ?? "-"}..{max?.ToString() ?? "-"}]를 벗어났습니다.");
        }

        private static Exception Empty(string table, string column)
            => new InvalidDataException($"[{table}.{column}] 셀이 비었는데 Default(Null) 값이 없습니다.");

        private static Exception Invalid(string table, string column, string type, string cell)
            => new InvalidDataException($"[{table}.{column}] {type} 파싱 실패: '{cell}'");
    }
}
