using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace MikaSourceGen
{
    // [Packet] -> 타입↔Id 매핑 코드 (GeneratedPacketIds.g.cs)
    // 트리거가 [Packet] 타입이라서 패킷 정의가 사는 프로젝트(MikaProtocol)에서 생성된다.
    public sealed partial class PacketHandlerGenerator
    {
        // [Packet]이 붙은 타입 1개 -> (패킷 타입, Id)
        static PacketIdInfo? ExtractPacketId(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol t) return null;

            var pAttr = ctx.Attributes.FirstOrDefault();
            if (pAttr is null || pAttr.ConstructorArguments.Length == 0) return null;

            return new PacketIdInfo(
                PacketType: t.ToDisplayString(),
                IdRef: ResolveIdRef(pAttr.ConstructorArguments[0]));
        }

        static void EmitPacketIds(SourceProductionContext spc, ImmutableArray<PacketIdInfo> packets)
        {
            if (packets.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using MikaProtocol;");
            sb.AppendLine();
            sb.AppendLine("namespace MikaGenerated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedPacketIds");
            sb.AppendLine("    {");
            sb.AppendLine("        public static ushort Get<T>() where T : IPacket => PacketId<T>.Value;");
            sb.AppendLine();
            sb.AppendLine("        static class PacketId<T> where T : IPacket");
            sb.AppendLine("        {");
            sb.AppendLine("            public static readonly ushort Value = Resolve();");
            sb.AppendLine();
            sb.AppendLine("            static ushort Resolve()");
            sb.AppendLine("            {");
            foreach (var p in packets)
                sb.AppendLine($"                if (typeof(T) == typeof({p.PacketType})) return (ushort){p.IdRef};");
            sb.AppendLine("                throw new InvalidOperationException($\"{typeof(T).Name}에 [Packet]이 없습니다\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedPacketIds.g.cs", sb.ToString());
        }

        // 증분 캐시를 위한 값 동등성. C# 9(Unity)에서도 쓰려고 record struct 대신
        // readonly struct + IEquatable<T>를 직접 구현한다.
        private readonly struct PacketIdInfo : System.IEquatable<PacketIdInfo>
        {
            public readonly string PacketType;
            public readonly string IdRef;

            public PacketIdInfo(string PacketType, string IdRef)
            {
                this.PacketType = PacketType;
                this.IdRef = IdRef;
            }

            public bool Equals(PacketIdInfo other) =>
                PacketType == other.PacketType &&
                IdRef == other.IdRef;

            public override bool Equals(object? obj) => obj is PacketIdInfo other && Equals(other);

            public override int GetHashCode()
            {
                unchecked
                {
                    int hash = 17;
                    hash = hash * 31 + (PacketType?.GetHashCode() ?? 0);
                    hash = hash * 31 + (IdRef?.GetHashCode() ?? 0);
                    return hash;
                }
            }
        }
    }
}
