using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace MikaSourceGen
{
    // [PacketHandler] -> 핸들러 등록 코드 (GeneratedHandlers.g.cs)
    // 트리거가 메서드라서 [PacketHandler]를 가진 프로젝트(서버/클라)에서만 생성된다.
    public sealed partial class PacketHandlerGenerator
    {
        // 핸들러 메서드 1개 -> (패킷 타입, Id, MethodRef)
        static HandlerInfo? ExtractHandler(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IMethodSymbol m) return null;
            if (m.Parameters.Length != 2 || !m.IsStatic) return null; // (MikaSession, IPacket), static

            var packetType = m.Parameters[1].Type;

            var pAttr = packetType.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == PacketAttr);

            if (pAttr is null || pAttr.ConstructorArguments.Length == 0) return null;

            // 소스에 있는 선언만 위치로 쓴다(메타데이터 위치는 파일이 아니다).
            Location? declLocation = null;
            foreach (var l in m.Locations)
            {
                if (l.IsInSource) { declLocation = l; break; }
            }

            return new HandlerInfo(
                PacketType: packetType.ToDisplayString(),
                IdRef: ResolveIdRef(pAttr.ConstructorArguments[0]),
                MethodRef: $"{m.ContainingType.ToDisplayString()}.{m.Name}",
                DeclLocation: declLocation);
        }

        static void EmitHandlers(SourceProductionContext spc, ImmutableArray<HandlerInfo> handlers)
        {
            if (handlers.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using MikaNetwork;");
            sb.AppendLine();
            sb.AppendLine("namespace MikaGenerated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedHandlers");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void RegisterAll(MikaPacketManager manager)");
            sb.AppendLine("        {");
            foreach (var h in handlers)
                sb.AppendLine($"            manager.Register<{h.PacketType}>((ushort){h.IdRef}, {h.MethodRef});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedHandlers.g.cs", sb.ToString());
        }

        // 증분 캐시를 위한 값 동등성. C# 9(Unity)에서도 쓰려고 record struct 대신
        // readonly struct + IEquatable<T>를 직접 구현한다.
        private readonly struct HandlerInfo : System.IEquatable<HandlerInfo>
        {
            public readonly string PacketType;
            public readonly string IdRef;
            public readonly string MethodRef;

            /// <summary>
            /// 핸들러 메서드의 선언 위치. MIKA001 경고에서 <b>대체 위치</b>로 쓴다.
            /// 패킷 정의가 참조 어셈블리에 있으면(서버 빌드) 패킷 쪽 위치를 잡을 수 없는데,
            /// 위치 없는 진단은 "CSC : warning ..." 형태로 나와 Unity 콘솔에서 사라진다.
            /// "핸들러를 여기에 추가하라"는 뜻이기도 해서 안내 위치로도 알맞다.
            /// </summary>
            public readonly Location? DeclLocation;

            public HandlerInfo(string PacketType, string IdRef, string MethodRef, Location? DeclLocation)
            {
                this.PacketType = PacketType;
                this.IdRef = IdRef;
                this.MethodRef = MethodRef;
                this.DeclLocation = DeclLocation;
            }

            public bool Equals(HandlerInfo other) =>
                PacketType == other.PacketType &&
                IdRef == other.IdRef &&
                MethodRef == other.MethodRef &&
                Equals(DeclLocation, other.DeclLocation);

            public override bool Equals(object? obj) => obj is HandlerInfo other && Equals(other);

            public override int GetHashCode()
            {
                unchecked
                {
                    int hash = 17;
                    hash = hash * 31 + (PacketType?.GetHashCode() ?? 0);
                    hash = hash * 31 + (IdRef?.GetHashCode() ?? 0);
                    hash = hash * 31 + (MethodRef?.GetHashCode() ?? 0);
                    return hash;
                }
            }
        }
    }
}
