// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel(Enum.xlsx)로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

namespace GameData
{
    public enum ItemType : byte
    {
        None    = 0,

        Farming = 1,  // 농사
        Fishing = 2,  // 낚시
        Mining  = 3,  // 채광
        Logging = 4,  // 벌목
        Hunting = 5,  // 사냥
        Misc    = 6,  // 기타
        Special = 7,  // 특수

        Max    ,
    };

    public enum GlobalRarity : byte
    {
        None      = 0,

        Common    = 1,  // 일반, 흰색/회색 #9D9D9D
        Uncommon  = 2,  // 고급, 초록 #1EFF00
        Rare      = 3,  // 희귀, 파랑 #0070DD
        Epic      = 4,  // 영웅, 보라 #A335EE
        Legendary = 5,  // 전설, 주황/금색 #FF8000
        Mythic    = 6,  // 신화, 빨강/핑크 #E6CC80

        Max      ,
    };

    public enum CurrencyType : byte
    {
        None = 0,

        Gold = 1,  // 골드

        Max ,
    };
}
