// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>FishingBasicTable 테이블의 한 행. FishingBasicTable.bytes = MemoryPackSerializer.Serialize(List&lt;FishingBasicTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class FishingBasicTableRow
    {
        public int    DropTID       { get; set; }        // int
        public int    IndustryLevel { get; set; }        // int [1..5]
        public int    ItemTID       { get; set; }        // int
        public int    Weight        { get; set; }        // int
        public string Description   { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
