// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>GachaTable 테이블의 한 행. GachaTable.bytes = MemoryPackSerializer.Serialize(List&lt;GachaTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class GachaTableRow
    {
        public int    GachaTID    { get; set; }        // int
        public int    GachaId     { get; set; }        // int [1..-]
        public int    ItemTID     { get; set; }        // int
        public int    Count       { get; set; }        // int [1..-]
        public int    Weight      { get; set; }        // int
        public string Description { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
