// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>IndustryLevelTable 테이블의 한 행. IndustryLevelTable.bytes = MemoryPackSerializer.Serialize(List&lt;IndustryLevelTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class IndustryLevelTableRow
    {
        public int      IndustryLevelTID     { get; set; }        // int
        public ItemType IndustryType         { get; set; }        // eItemType
        public int      Level                { get; set; }        // int [1..5]
        public string   Name                 { get; set; } = "";  // string
        public int      RequiredScore        { get; set; }        // int [1..-]
        public int      RequiredAptitude     { get; set; }        // int [0..10]
        public int      RequiredAccountLevel { get; set; }        // int [0..-]
        public string   Description          { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
