// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>WorkSpeedTable 테이블의 한 행. WorkSpeedTable.bytes = MemoryPackSerializer.Serialize(List&lt;WorkSpeedTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class WorkSpeedTableRow
    {
        public int    WorkSpeedTID          { get; set; }        // int [0..-]
        public int    BaseWorkSpeedPermille { get; set; }        // int [0..-]
        public string Description           { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
